rabbit1:
  image: tutum/rabbitmq
  hostname: rabbit1
  environment:
    - RABBITMQ_PASS=PASSWORD
  ports:
    - "5673:5672"
    - "15673:15672"
mongo:
  image: mongo
  hostname: mongo
portal:
  image: nome-imagem
  hostname: host-imagem
  ports:
    - "7070:8080"
    - "9990:9990"
  links:
    - "rabbit1"
    - "mongo"
